### ISSUE TITLE
Testing of the project

### ISSUE THREAD

**Issue by BY-hash** [alceubissoto/gan-skin-lesion#4]
Hello, 
To my understanding the testing was done on Inception-V4.
However, it seems you have used the 2018 Task 2 data for the testing - but this data has no labels (only 5 attribute maps as ground truth)
Is the classification as malignant or benign was done on another data?

Thank you!

**Comment by alceubissoto** [comment]
Sorry for the BIG delay... You can get the labels of the set using the Task3 labels.

Bests,
